spring:
  config:
    import:
  application:
    name: oops

  profiles:
    active: local
    include: rds, dev, jwt
  #jpa
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
       ddl-auto: update