spring:
  config:
    import:
      - "classpath:application-security.yml"
  application:
    name: oops

  profiles:
    active: local
    include: dev
  #jpa
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
       ddl-auto: update